=== GregSal/PyParameters/GUI_Management/GUI_Builder.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:include schemaLocation="Tkinter_GUI.xsd" />
  <xs:complexType name="VariableType">
    <xs:sequence>
      <xs:element name="variable_class" type="xs:string" />
      <xs:element minOccurs="0" name="data_reference" type="xs:string" />
    </xs:sequence>
    <xs:attribute name="name" type="xs:string" use="required" />
  </xs:complexType>
  <xs:complexType name="CommandType">
    <xs:sequence>
      <xs:element name="function" type="xs:string" />
      <xs:element minOccurs="1" maxOccurs="1" name="PositionalArgs">
        <xs:complexType>
          <xs:sequence minOccurs="0">
            <xs:element name="Arg" type="xs:string" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element minOccurs="1" maxOccurs="1" name="KeywordArgs">
        <xs:complexType>
          <xs:anyAttribute namespace="" processContents="skip" />
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="name" type="xs:string" use="required" />
  </xs:complexType>
  <xs:complexType name="ImageType">
    <xs:attribute name="name" type="xs:string" />
  </xs:complexType>
  <xs:element name="GuiDefinition">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="1" name="VariableSet">
          <xs:complexType>
            <xs:sequence>
              <xs:element minOccurs="1" maxOccurs="unbounded" name="Variable" type="VariableType" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element minOccurs="0" maxOccurs="1" name="ImageSet">
          <xs:complexType>
            <xs:sequence>
              <xs:element minOccurs="1" maxOccurs="unbounded" name="Image" type="ImageType" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element minOccurs="0" maxOccurs="1" name="CommandSet">
          <xs:complexType>
            <xs:sequence>
              <xs:element minOccurs="1" maxOccurs="unbounded" name="Command" type="CommandType" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element minOccurs="1" maxOccurs="1" name="RootWindow">
          <xs:complexType>
            <xs:complexContent mixed="false">
              <xs:extension base="WindowType">
                <xs:sequence>
                  <xs:element minOccurs="0" maxOccurs="unbounded" name="Window" type="WindowType" />
                </xs:sequence>
              </xs:extension>
            </xs:complexContent>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="WidgetSet">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" name="FunctionalWidget" type="WidgetType">
          <xs:annotation>
            <xs:documentation>The Functional Widget is for interactive widgets.
Examples are Button, Label, Entry.</xs:documentation>
          </xs:annotation>
        </xs:element>
        <xs:element minOccurs="0" maxOccurs="unbounded" name="Tree" type="TreeWidget" />
        <xs:element minOccurs="0" maxOccurs="unbounded" name="ContainerWidget" type="ContainerWidgetType">
          <xs:annotation>
            <xs:documentation xml:lang="EN">The container Widget is for widgets used to store other widgets.
Examples are Frame, LabelFrame and Canvas</xs:documentation>
          </xs:annotation>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Configure">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" name="Set">
          <xs:complexType>
            <xs:simpleContent>
              <xs:extension base="xs:string">
                <xs:anyAttribute processContents="skip" />
              </xs:extension>
            </xs:simpleContent>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:anyAttribute processContents="skip" />
    </xs:complexType>
  </xs:element>
  <xs:complexType name="AppearanceType">
    <xs:attribute name="borderwidth" type="xs:unsignedByte" use="optional" />
    <xs:attribute name="relief" type="xs:string" use="optional" />
    <xs:attribute name="background" type="xs:string" use="optional" />
    <xs:attribute name="foreground" type="xs:string" use="optional" />
    <xs:attribute name="image" type="xs:string" use="optional" />
  </xs:complexType>
  <xs:complexType name="GridConfigureType">
    <xs:sequence>
      <xs:element name="ColumnConfigure">
        <xs:complexType>
          <xs:attribute name="column" type="xs:unsignedInt" />
          <xs:attribute name="weight" type="xs:unsignedInt" use="required" />
        </xs:complexType>
      </xs:element>
      <xs:element name="RowConfigure">
        <xs:complexType>
          <xs:attribute name="row" type="xs:unsignedInt" />
          <xs:attribute name="weight" type="xs:unsignedInt" use="required" />
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="WindowType">
    <xs:sequence>
      <xs:element minOccurs="0" name="Settings">
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs="0" maxOccurs="1" name="title" type="xs:string" />
            <xs:choice minOccurs="0" maxOccurs="1">
              <xs:element minOccurs="0" maxOccurs="1" name="Fullscreen" />
              <xs:element minOccurs="0" maxOccurs="1" name="Geometry" type="WindowGeometryType" />
            </xs:choice>
            <xs:element minOccurs="0" maxOccurs="1" name="State" type="StateType" />
            <xs:element minOccurs="0" name="Appearance" type="AppearanceType" />
            <xs:element minOccurs="0" name="GridConfigure" type="GridConfigureType" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element minOccurs="0" maxOccurs="1" ref="Configure" />
      <xs:element minOccurs="0" ref="WidgetSet" />
    </xs:sequence>
    <xs:attribute name="name" type="xs:string" use="required" />
  </xs:complexType>
  <xs:complexType name="WindowGeometryType">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="1" name="Height" type="xs:unsignedInt" />
      <xs:element minOccurs="0" maxOccurs="1" name="Width" type="xs:unsignedInt" />
      <xs:element minOccurs="0" maxOccurs="1" name="Xposition" type="xs:int" />
      <xs:element minOccurs="0" maxOccurs="1" name="Yposition" type="xs:int" />
      <xs:element minOccurs="0" name="Stacking">
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs="0" maxOccurs="1" name="lift" type="xs:string" />
            <xs:element minOccurs="0" maxOccurs="1" name="lower" type="xs:string" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:simpleType name="StateType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="normal" />
      <xs:enumeration value="iconic" />
      <xs:enumeration value="withdrawn" />
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="WidgetType">
    <xs:sequence>
      <xs:element minOccurs="1" maxOccurs="1" name="widget_class" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="Settings">
        <xs:complexType>
          <xs:all>
            <xs:element minOccurs="0" name="Geometry" type="WidgetGeometryType" />
            <xs:element minOccurs="0" name="Appearance" type="AppearanceType" />
            <xs:element minOccurs="0" name="Bindings" type="BindingsType" />
          </xs:all>
        </xs:complexType>
      </xs:element>
      <xs:element minOccurs="0" maxOccurs="1" ref="Configure" />
    </xs:sequence>
    <xs:attribute name="name" type="xs:string" use="required" />
  </xs:complexType>
  <xs:complexType name="WidgetGeometryType">
    <xs:sequence>
      <xs:element minOccurs="1" maxOccurs="1" name="Placement">
        <xs:complexType>
          <xs:choice>
            <xs:element name="GridPlacement">
              <xs:complexType>
                <xs:attribute name="column" type="xs:unsignedInt" use="required" />
                <xs:attribute name="row" type="xs:unsignedInt" use="required" />
                <xs:attribute name="columnspan" type="xs:unsignedInt" use="optional" />
                <xs:attribute name="rowspan" type="xs:unsignedInt" use="optional" />
                <xs:attribute name="sticky" type="StickyType" use="optional" />
              </xs:complexType>
            </xs:element>
            <xs:element name="PackPlacement">
              <xs:complexType>
                <xs:attribute name="anchor" type="xs:string" use="required" />
              </xs:complexType>
            </xs:element>
          </xs:choice>
        </xs:complexType>
      </xs:element>
      <xs:element minOccurs="0" maxOccurs="1" name="Padding">
        <xs:complexType>
          <xs:attribute name="ipadx" type="xs:unsignedByte" use="required" />
          <xs:attribute name="ipady" type="xs:unsignedByte" use="required" />
          <xs:attribute name="padx" type="xs:unsignedByte" use="required" />
          <xs:attribute name="pady" type="xs:unsignedByte" use="required" />
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:simpleType name="StickyType">
    <xs:restriction base="xs:string">
      <xs:pattern value="[nsew]{1,4}" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="AnchorType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="n" />
      <xs:enumeration value="ne" />
      <xs:enumeration value="e" />
      <xs:enumeration value="se" />
      <xs:enumeration value="s" />
      <xs:enumeration value="sw" />
      <xs:enumeration value="w" />
      <xs:enumeration value="nw" />
      <xs:enumeration value="center" />
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="BindingsType">
    <xs:sequence>
      <xs:element minOccurs="1" maxOccurs="unbounded" name="Bind">
        <xs:complexType>
          <xs:attribute name="event" type="xs:string" use="required" />
          <xs:attribute name="callback" type="xs:string" use="required" />
          <xs:attribute name="add" type="xs:string" use="optional" />
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="ContainerWidgetType">
    <xs:complexContent mixed="false">
      <xs:extension base="WidgetType">
        <xs:sequence>
          <xs:element minOccurs="0" name="GridConfigure" type="GridConfigureType" />
          <xs:element minOccurs="0" maxOccurs="1" ref="WidgetSet" />
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
</xs:schema>

=== GregSal/PyParameters/GUI_Management/FileSelectFrame.xml
<?xml version="1.0" encoding="utf-8"?>
<!-- Created with Liquid Studio 2019 (https://www.liquid-technologies.com) -->
<GuiDefinition xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:noNamespaceSchemaLocation="file:./GUI_Builder.xsd">
    <VariableSet>
        <Variable name="FileName">
            <variable_class>tk.StringVar</variable_class>
        </Variable>
    </VariableSet>
    <CommandSet>
        <Command name="Exit">
            <function>W::root.destroy</function>
            <PositionalArgs />
            <KeywordArgs />
        </Command>
        <Command name="ShowText">
            <function>fg.message_window</function>
            <PositionalArgs>
                <Arg>W::root</Arg>
            </PositionalArgs>
            <KeywordArgs window_text="Message"
                         variable="V::Output"/>
        </Command>
    </CommandSet>
    <RootWindow name="root">
        <Settings>
            <title>Main GUI</title>
            <Geometry>
                <Height>768</Height>
                <Width>1024</Width>
            </Geometry>
            <State>normal</State>
            <Appearance background='light blue'/>
            <GridConfigure>
                <ColumnConfigure column='0'
                                 weight='1'/>
                <RowConfigure row='0'
                              weight='1'/>
            </GridConfigure>
        </Settings>
        <WidgetSet>
            <Widget name="exit_button">
                <widget_class>ttk.Button</widget_class>
                <Configure text="Egress"
                           command="C::Exit"/>
                <Settings>
                    <Geometry>
                        <Placement>
                            <GridPlacement column="0"
                                           row="3"/>
                        </Placement>
                    </Geometry>
                </Settings>
            </Widget>
            <Widget name="test_entry">
                <widget_class>ttk.Entry</widget_class>
                <Configure textvariable="V::Output"/>
                <Settings>
                    <Geometry>
                        <Placement>
                            <GridPlacement column="0"
                                           row="0"/>
                        </Placement>
                    </Geometry>
                </Settings>
            </Widget>
            <Widget name="text_button">
                <widget_class>ttk.Button</widget_class>
                <Configure text="Display"
                           command="C::ShowText"/>
                <Settings>
                    <Geometry>
                        <Placement>
                            <GridPlacement column="1"
                                           row="0"
                                           rowspan="2"/>
                        </Placement>
                    </Geometry>
                </Settings>
            </Widget>
            <Widget name="test_label">
                <widget_class>ttk.Label</widget_class>
                <Configure textvariable="V::Output"/>
                <Settings>
                    <Geometry>
                        <Placement>
                            <GridPlacement column="0"
                                           row="1"/>
                        </Placement>
                    </Geometry>
                </Settings>
            </Widget>
        </WidgetSet>
    </RootWindow>
</GuiDefinition>

=== GregSal/PyParameters/GUI_Management/TestGUI.xml
<?xml version="1.0" encoding="utf-8"?>
<GuiDefinition xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:noNamespaceSchemaLocation="file:./GUI_Builder.xsd">
  <VariableSet>
    <Variable name="Output">
      <variable_class>T::tk.StringVar</variable_class>
      <data_reference>test_string</data_reference>
    </Variable>
  </VariableSet>
  <CommandSet>
    <Command name="Exit">
      <function>W::root.destroy</function>
      <PositionalArgs />
      <KeywordArgs />
    </Command>
    <Command name="ShowText">
      <function>T::fg.message_window</function>
      <PositionalArgs>
        <Arg>W::root</Arg>
      </PositionalArgs>
      <KeywordArgs window_text="Message"
                   variable="V::Output"/>
    </Command>
  </CommandSet>
  <RootWindow name="root">
    <Settings>
      <title>Root</title>
      <Fullscreen>true</Fullscreen>
      <State>iconic</State>
      <Appearance background="white"/>
    </Settings>
    <WindowSet>
      <Window name="main_gui">
        <Settings>
          <title>Main GUI</title>
          <Geometry>
            <Height>768</Height>
            <Width>1024</Width>
            <Stacking>
              <lift>W::root</lift>
            </Stacking>
          </Geometry>
          <State>normal</State>
          <Appearance background='light blue'/>
          <GridConfigure>
            <ColumnConfigure column='0'
                             weight='1'/>
            <RowConfigure row='0'
                          weight='1'/>
          </GridConfigure>
        </Settings>
        <WidgetSet>
          <Widget name="size_grip">
            <widget_class>T::ttk.Sizegrip</widget_class>
            <Settings>
              <Geometry>
                <Grid row="3"
                      column="3"/>
              </Geometry>
            </Settings>
          </Widget>
          <Widget name="exit_button">
            <widget_class>T::ttk.Button</widget_class>
            <Configure text="Egress"
                       command="C::Exit"/>
            <Settings>
              <Geometry>
                <Grid column="0"
                      row="3"/>
              </Geometry>
            </Settings>
          </Widget>
          <Widget name="test_entry">
            <widget_class>T::ttk.Entry</widget_class>
            <Configure textvariable="V::Output"/>
            <Settings>
              <Geometry>
                <Grid column="0"
                      row="0"/>
              </Geometry>
            </Settings>
          </Widget>
          <Widget name="text_button">
            <widget_class>T::ttk.Button</widget_class>
            <Configure text="Display"
                       command="C::ShowText"/>
            <Settings>
              <Geometry>
                <Grid column="1"
                      row="0"
                      rowspan="2"/>
              </Geometry>
            </Settings>
          </Widget>
          <Widget name="test_label">
            <widget_class>T::ttk.Label</widget_class>
            <Configure textvariable="V::Output"/>
            <Settings>
              <Geometry>
                <Grid column="0"
                      row="1"/>
              </Geometry>
            </Settings>
          </Widget>
        </WidgetSet>
      </Window>
    </WindowSet>
    <WidgetSet>
      <Widget name="exit_button">
        <widget_class>T::ttk.Button</widget_class>
        <Configure text="Egress"
                   command="C::Exit"/>
        <Settings>
          <Geometry>
            <Grid column="0"
                  row="3"/>
          </Geometry>
        </Settings>
      </Widget>
    </WidgetSet>
  </RootWindow>
</GuiDefinition>
